name: Run Python Script and Deploy

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'

      - name: Run script
        run: python scripts/script.py

      - name: Commit changes to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commit: update from script" || echo "No changes to commit"
          git push origin main

  deploy-gh-pages:
    needs: run-script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Fetch formatted files and index.html from main
        run: |
          git fetch origin main

          # Clean existing folders
          rm -rf chats lore index.html

          # Checkout only necessary files from main
          git checkout origin/main -- chats/formatted lore/formatted index.html

          # Move contents of formatted/ up one level
          mkdir -p chats lore
          mv chats/formatted/* chats/ || true
          mv lore/formatted/* lore/ || true
          rm -rf chats/formatted lore/formatted

      - name: Commit changes to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add chats lore index.html
          git commit -m "Update gh-pages content from main" || echo "No changes to commit"
          git push origin gh-pages
